postgres:
  tag: 17.6

rocketmq:
  tag: 5.3.3
  nameserver:
    args: ["-c", "cd /home/rocketmq/rocketmq-5.3.3/bin && export JAVA_OPT=\"-Duser.home=/home/rocketmq\" && sh mqnamesrv"]
  broker:
    args: ["-c", "cd /home/rocketmq/rocketmq-5.3.3/bin && export JAVA_OPT=\"-Duser.home=/home/rocketmq -Drocketmq.namesrv.addr=rocketmq-nameserver:9876 -Drocketmq.broker.config=/home/rocketmq/rocketmq-5.3.3/conf/broker.conf\" && sh mqbroker -c /home/rocketmq/rocketmq-5.3.3/conf/broker.conf"]
  volumeMounts:
    config:
      mountPath: /home/rocketmq/rocketmq-5.3.3/conf/broker.conf
