apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-link  # Deployment 的名称
spec:
  replicas: 1  # 初始副本数量，根据需要修改
  selector:
    matchLabels:
      app: trade-link  # 这个标签必须和下面的 template.metadata.labels 匹配
  template:
    metadata:
      labels:
        app: trade-link  # Pod 的标签，Service 会根据这个来选择 Pod
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: trade-link  # 容器的名称
        image: shenyun2025/trade-link:0.0.3  # 你的 Docker Hub 镜像地址
        ports:
        - containerPort: 8082  # 你的应用在容器内监听的端口号（根据你的实际情况修改！）
        env:
        - name: SPRING_PROFILES_ACTIVE  # 设置环境变量
          value: "prod"
        # 以下资源配置可以根据需要添加或删除
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: trade-link  # Service 的名称
spec:
  selector:
    app: trade-link  # 这个标签必须和 Deployment 中的 Pod 标签匹配，用于寻找要代理的 Pod
  ports:
    - protocol: TCP
      port: 80          # Service 对外暴露的端口
      targetPort: 8082  # 请求转发到 Pod 的端口（必须与 Deployment 中的 containerPort 一致）
  type: ClusterIP       # 默认类型，只能在集群内部访问
