spring:
  datasource:
    url: jdbc:postgresql://192.168.5.19:5432/trade-link
    username: postgres
    password: postgres_Password
rocketmq:
  name-server: 192.168.5.19:9876
oms:
  host: http://localhost:8083