spring:
  datasource:
#    url: jdbc:mysql://mysql-service:3306/trade-link?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://postgres-service:5432/trade-link
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
rocketmq:
  name-server: rocketmq-nameserver:9876
oms:
  host: http://oms