apiVersion: apps/v1
kind: Deployment
metadata:
  name: fix-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fix-engine
  template:
    metadata:
      labels:
        app: fix-engine
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
      - name: wait-for-rocketmq-nameserver
        image: busybox
        command: ['sh', '-c', 'until nc -z rocketmq-nameserver 9876; do echo "Waiting for RocketMQ NameServer..."; sleep 2; done;']
      containers:
      - name: fix-engine
        image: shenyun2025/fix-engine:{{ .Values.image.tag.fix_engine }}
        ports:
        - containerPort: 8085
        - containerPort: 8086
        # 健康检查探针配置
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 0
          periodSeconds: 3
          failureThreshold: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 0
          periodSeconds: 3
          failureThreshold: 5
          timeoutSeconds: 2
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 45
          failureThreshold: 3
          periodSeconds: 5
          timeoutSeconds: 3
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.env}}
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: fix-engine
spec:
  selector:
    app: fix-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
