apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement-service
  template:
    metadata:
      labels:
        app: settlement-service
        deployment-group: order-system
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      # 添加亲和性配置
      affinity:
        podAffinity:
          # 使用 preferredDuringScheduling 软策略，尽量满足，不强制
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100 # 权重，表示优先级很高
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: deployment-group # 寻找带有这个标签的Pod
                  operator: In
                  values:
                  - order-system        # 标签的值
              # 拓扑域为节点级别，确保在同一个Node上
              topologyKey: kubernetes.io/hostname
      containers:
      - name: settlement-service
        image: shenyun2025/settlement-service:{{ .Values.image.tag.settlement_service }}
        ports:
        - containerPort: 8084
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: settlement-service
spec:
  selector:
    app: settlement-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
