apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbg  # Deployment 的名称
spec:
  replicas: 1  # 初始副本数量，根据需要修改
  selector:
    matchLabels:
      app: bbg  # 这个标签必须和下面的 template.metadata.labels 匹配
  template:
    metadata:
      labels:
        app: bbg  # Pod 的标签，Service 会根据这个来选择 Pod
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: bbg  # 容器的名称
        image: shenyun2025/bbg:latest  # 你的 Docker Hub 镜像地址
        env:
        - name: SPRING_PROFILES_ACTIVE  # 设置环境变量
          value: "prod"
        # 以下资源配置可以根据需要添加或删除
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
