spring:
  datasource:
    url: jdbc:postgresql://192.168.71.43:5432/tps2
    username: postgres
    password: postgres_Password
rocketmq:
  name-server: 192.168.71.43:9876
settlement:
  host: http://localhost:8084