spring:
  datasource:
#    url: jdbc:mysql://mysql-service:3306/tps2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://postgres-service:5432/tps2
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
rocketmq:
  name-server: rocketmq-nameserver:9876
settlement:
  host: http://settlement-service